name: 1st-try
favicon: null
layout_spectrum: 0.9889048710465431
typography_spectrum: 0.15227762633003294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6589513788931072
  lightness: 0.050524834310635924
  saturation: 0.36952195037156343
  rhythmicContrast: 0.012502547353506088
purpose: []
